# This is a MongoDB service that is used by the other pods in the cluster to find and connect to MongoDB
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017